name: Release
on: push


jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-10.15, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      # - run: npm i node-sass
      # - run: npm install

      # - name: Build and release
      #   uses: tauri-apps/tauri-action@v0.3
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
      #   with:
      #     tagName: v${{github.ref_name}}
      #     releaseName: v${{github.ref_name}}
      #     releaseDraft: true
      #     prerelease: false
      #     projectPath: ./
          # releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}

      - name: install app dependencies and build it
        run: yarn install --network-timeout 1000000 && yarn build

      - name: tauri run
        uses: tauri-apps/tauri-action@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tagName: v${{github.ref_name}}
        #   releaseName: v${{github.ref_name}}
        #   releaseDraft: true
        #   prerelease: false


