name: release-tauri-app

on: push

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    env:
      working-directory: ./

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      # - name: install app dependencies and build it
      #   run: yarn && yarn build
      #   working-directory: ${{env.working-directory}}
      - run: yarn
      - name: build nota for tauri app
        run: yarn build
      - run: cargo install tauri-bundler --force
      - name: build tauri app
        run: yarn tauri:build
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          projectPath: ${{env.working-directory}}